version: '2'

services:
  web-challenge:
    build: .
    restart: always
    volumes:
      - ./dns:/dns
    ports:
      - "80:80"
      - "53:53"
      - "53:53/udp"
    networks:
        default:  

networks:
    default: